apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: c719f5qxl-nodejs
  janus-idp.io/tekton: c719f5qxl-nodejs
  backstage.io/kubernetes-id: c719f5qxl-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: c719f5qxl-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
